<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SantriSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'foto'                  => '',
                'nama'                  => 'Abella Zahra',
                'nisn'                  => '0102100612',
                'nism'                  => '131232150027240102',
                'kewarganegaraan'       => 'WNI',
                'nik'                   => '3215125401100001',
                'tempat_lahir'          => 'Karawang',
                'tanggal_lahir'         => '2010-01-14',
                'jenis_kelamin'         => 'perempuan',
                'jumlah_saudara_kandung' => '1',
                'anak_ke'               => '1',
                'agama'                 => 'islam',
                'hobi'                  => 'membaca',
                'aktivitas_pendidikan'  => 'aktif',
                'npsn'                  => '70047049',
                'no_kip'                => 'MA Daarul Huffazh',
                'no_kk'                 => '3215122808070100',
                'nama_kepala_keluarga'   => 'MAMA',
                'kelas_id'              => 1,
                'kamar_id'              => 1,
                'riwayat_penyakit'      => 'sehat',
                'status_kesantrian'     => 'aktif',
                'status_santri'         => 'reguler',
            ],
            [
                'foto'                  => '',
                'nama'                  => 'Afifah Shawatul Shawa',
                'nisn'                  => '',
                'nism'                  => '131232150027240103',
                'kewarganegaraan'       => 'WNI',
                'nik'                   => '3215086511080003',
                'tempat_lahir'          => 'Karawang',
                'tanggal_lahir'         => '2008-11-25',
                'jenis_kelamin'         => 'perempuan',
                'jumlah_saudara_kandung' => '1',
                'anak_ke'               => '1',
                'agama'                 => 'islam',
                'hobi'                  => 'kesenian',
                'aktivitas_pendidikan'  => 'aktif',
                'npsn'                  => '70047049',
                'no_kip'                => 'MA Daarul Huffazh',
                'no_kk'                 => '3215080304190021',
                'nama_kepala_keluarga'   => 'ROHATI',
                'kelas_id'              => 1,
                'kamar_id'              => 1,
                'riwayat_penyakit'      => 'sehat',
                'status_kesantrian'     => 'aktif',
                'status_santri'         => 'reguler',
            ],
            [
                'foto'                  => '',
                'nama'                  => 'Amelia Solihah',
                'nisn'                  => '0092368296',
                'nism'                  => '131232150027240107',
                'kewarganegaraan'       => 'WNI',
                'nik'                   => '3215045205090001',
                'tempat_lahir'          => 'Karawang',
                'tanggal_lahir'         => '2009-06-12',
                'jenis_kelamin'         => 'perempuan',
                'jumlah_saudara_kandung' => '2',
                'anak_ke'               => '1',
                'agama'                 => 'islam',
                'hobi'                  => 'menulis',
                'aktivitas_pendidikan'  => 'aktif',
                'npsn'                  => '70047049',
                'no_kip'                => 'MA Daarul Huffazh',
                'no_kk'                 => '3215040610070074',
                'nama_kepala_keluarga'   => 'SAEPULLOH',
                'kelas_id'              => 1,
                'kamar_id'              => 1,
                'riwayat_penyakit'      => 'sehat',
                'status_kesantrian'     => 'aktif',
                'status_santri'         => 'reguler',
            ],
            [
                'foto'                  => '',
                'nama'                  => 'Aufa Rizky Aulia Ramadhan',
                'nisn'                  => '0096136530',
                'nism'                  => '131232150027240108',
                'kewarganegaraan'       => 'WNI',
                'nik'                   => '3215092908090002',
                'tempat_lahir'          => 'Karawang',
                'tanggal_lahir'         => '2009-08-29',
                'jenis_kelamin'         => 'perempuan',
                'jumlah_saudara_kandung' => '2',
                'anak_ke'               => '1',
                'agama'                 => 'islam',
                'hobi'                  => 'olahraga',
                'aktivitas_pendidikan'  => 'aktif',
                'npsn'                  => '70047049',
                'no_kip'                => 'MA Daarul Huffazh',
                'no_kk'                 => '3215231203180010',
                'nama_kepala_keluarga'   => 'WINATA',
                'kelas_id'              => 1,
                'kamar_id'              => 1,
                'riwayat_penyakit'      => 'sehat',
                'status_kesantrian'     => 'aktif',
                'status_santri'         => 'reguler',
            ],
            [
                'foto'                  => '',
                'nama'                  => 'Bima Sanjaya',
                'nisn'                  => '0091236343',
                'nism'                  => '131232150027240109',
                'kewarganegaraan'       => 'WNI',
                'nik'                   => '3172041912080001',
                'tempat_lahir'          => 'Tasikmalaya',
                'tanggal_lahir'         => '2008-12-19',
                'jenis_kelamin'         => 'laki-laki',
                'jumlah_saudara_kandung' => '4',
                'anak_ke'               => '1',
                'agama'                 => 'islam',
                'hobi'                  => 'membaca',
                'aktivitas_pendidikan'  => 'aktif',
                'npsn'                  => '70047049',
                'no_kip'                => 'MA Daarul Huffazh',
                'no_kk'                 => '3327070903170010',
                'nama_kepala_keluarga'   => 'SARJIMIN',
                'kelas_id'              => 1,
                'kamar_id'              => 1,
                'riwayat_penyakit'      => 'sehat',
                'status_kesantrian'     => 'aktif',
                'status_santri'         => 'reguler',
            ],
            [
                'foto'                  => '',
                'nama'                  => 'Devita',
                'nisn'                  => '0097932577',
                'nism'                  => '131232150027240110',
                'kewarganegaraan'       => 'WNI',
                'nik'                   => '3215125111080002',
                'tempat_lahir'          => 'Karawang',
                'tanggal_lahir'         => '2008-08-11',
                'jenis_kelamin'         => 'perempuan',
                'jumlah_saudara_kandung' => '2',
                'anak_ke'               => '1',
                'agama'                 => 'islam',
                'hobi'                  => 'olahraga',
                'aktivitas_pendidikan'  => 'aktif',
                'npsn'                  => '70047049',
                'no_kip'                => 'MA Daarul Huffazh',
                'no_kk'                 => '',
                'nama_kepala_keluarga'   => '',
                'kelas_id'              => 1,
                'kamar_id'              => 1,
                'riwayat_penyakit'      => 'sehat',
                'status_kesantrian'     => 'aktif',
                'status_santri'         => 'reguler',
            ],
            // Add more data as necessary...
        ];

        DB::table('santris')->insert($data);
    }
}
